In [26]:
import pandas as pd

In [27]:
df = pd.read_csv("January2015toNovember2025.csv")

C:\Users\rezap\AppData\Local\Temp\ipykernel_35384\3024605332.py:1: DtypeWarning: Columns (0: Primary NAICS, 1: Inspection) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("January2015toNovember2025.csv")

In [28]:
df.head(5)

,ID,UPA,EventDate,Employer,Address1,Address2,City,State,Zip,Latitude,...,NatureTitle,Part of Body,Part of Body Title,Event,EventTitle,Source,SourceTitle,Secondary Source,Secondary Source Title,FederalState
0,2015010015,931176,1/1/2015,FCI Otisville Federal Correctional Institution,Two Mile Drive,NaN,OTISVILLE,NEW YORK,10963.0,41.46,...,Fractures,513,Lower leg(s),1214,Injured by physical contact with person while ...,5721,Co-worker,5772.0,Inmate or detainee in custody,1
1,2015010016,930267,1/1/2015,Kalahari Manufacturing LLC,171 Progress Drive,NaN,LAKE DELTON,WISCONSIN,53940.0,43.59,...,Second degree heat (thermal) burns,519,"Leg(s), n.e.c.",317,"Ignition of vapors, gases, or liquids",7261,"Welding, cutting, and blow torches",NaN,NaN,1
2,2015010018,929823,1/1/2015,Schneider National Bulk Carrier,420 CORAOPOLIS ROAD,NaN,CORAOPOLIS,PENNSYLVANIA,15108.0,40.49,...,"Traumatic injuries and disorders, unspecified",9999,Nonclassifiable,4331,Other fall to lower level less than 6 feet,8421,"Semi, tractor-trailer, tanker truck",741.0,Ladders-fixed,1
3,2015010019,929711,1/1/2015,PEPSI BOTTLING GROUP INC.,4541 HOUSTON AVE.,NaN,MACON,GEORGIA,31206.0,32.77,...,"Soreness, pain, hurt-nonspecified injury",510,"Leg(s), unspecified",640,Caught in or compressed by equipment or object...,8623,Pallet jack-powered,8420.0,"Truck-motorized freight hauling and utility, u...",1
4,2015010020,929642,1/1/2015,North American Pipe Corporation,210 South Arch Street,NaN,JANESVILLE,WISCONSIN,53545.0,42.67,...,Fractures,4429,"Finger(s), fingernail(s), n.e.c.",6411,Caught in running equipment or machinery durin...,350,"Metal, woodworking, and special material machi...",NaN,NaN,1

In [29]:
df.columns.tolist()

['ID',
 'UPA',
 'EventDate',
 'Employer',
 'Address1',
 'Address2',
 'City',
 'State',
 'Zip',
 'Latitude',
 'Longitude',
 'Primary NAICS',
 'Hospitalized',
 'Amputation',
 'Loss of Eye',
 'Inspection',
 'Final Narrative',
 'Nature',
 'NatureTitle',
 'Part of Body',
 'Part of Body Title',
 'Event',
 'EventTitle',
 'Source',
 'SourceTitle',
 'Secondary Source',
 'Secondary Source Title',
 'FederalState']

In [30]:
df.shape

(105996, 28)

In [31]:
df['Primary NAICS'].value_counts().head(15)

Primary NAICS
622110    1712
445110    1488
238210    1402
236220    1330
213112    1207
493110    1187
237310    1115
238160    1082
238220    1026
491110     981
561730     937
622110     755
213112     689
484121     657
236220     628
Name: count, dtype: int64

In [32]:
logistics_df = df[df["Primary NAICS"].astype(str).str.startswith(("493", "492", "484"))]

In [33]:
logistics_df.head(5)

,ID,UPA,EventDate,Employer,Address1,Address2,City,State,Zip,Latitude,...,NatureTitle,Part of Body,Part of Body Title,Event,EventTitle,Source,SourceTitle,Secondary Source,Secondary Source Title,FederalState
2,2015010018,929823,1/1/2015,Schneider National Bulk Carrier,420 CORAOPOLIS ROAD,NaN,CORAOPOLIS,PENNSYLVANIA,15108.0,40.49,...,"Traumatic injuries and disorders, unspecified",9999,Nonclassifiable,4331,Other fall to lower level less than 6 feet,8421,"Semi, tractor-trailer, tanker truck",741.0,Ladders-fixed,1
70,2015010095,930392,1/5/2015,Brookshire Grocery Company,1600 W. Southwest Loop 323,NaN,TYLER,TEXAS,75701.0,32.30,...,Fractures,52,Ankle(s),422,Fall on same level due to slipping,6660,"Parking lot, unspecified",9273.0,"Ice, sleet, snow",1
108,2015010145,930661,1/6/2015,"BVD, Inc.",1463 M Street,NaN,PENROSE,COLORADO,81240.0,38.40,...,"Traumatic injuries and disorders, unspecified",9999,Nonclassifiable,642,Compressed or pinched by shifting objects or e...,8421,"Semi, tractor-trailer, tanker truck",210.0,"Containers, unspecified",1
122,2015010161,930727,1/7/2015,Warren Transport,360 Indian Creek Road,NaN,BELGRADE,MONTANA,59714.0,45.79,...,Fractures,513,Lower leg(s),6261,Struck by or caught in swinging door or gate,4852,Liftgates,NaN,NaN,1
123,2015010162,930924,1/7/2015,Dart Trucking Company Inc.,11017 Market St.,NaN,NORTH LIMA,OHIO,44452.0,40.95,...,"Cuts, lacerations",20,"Neck, except internal location of diseases or ...",6252,Injured by slipping or swinging object held by...,7224,"Saws-powered, except chainsaws",NaN,NaN,1

In [34]:
logistics_df.to_csv("logestics_companies_all.csv",index = False)